version: '3.8'

services:

  # ======================
  # 📦 База данных
  # ======================
  postgres:
    image: postgres:17
    container_name: social_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: socialdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  # ======================
  # 🧠 Redis (для сессий)
  # ======================
  redis:
    image: redis:7
    container_name: social_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  # ======================
  # 🐘 Kafka & ZooKeeper
  # ======================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: social_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: social_kafka
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # ======================
  # 🚪 Gateway (Spring Cloud Gateway)
  # ======================
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    depends_on:
      - postgres
      - kafka
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: docker

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    container_name: chat-service
    depends_on:
      - user-service
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    depends_on:
      - kafka
    environment:
      SPRING_PROFILES_ACTIVE: docker

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway

    depends_on:
      - user-service
      - chat-service
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  pg_data:
