server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: RewriteResponseHeader
          args:
            name: Set-Cookie
            regexp: "Path=/.*"
            replacement: "Path=/"
      routes:
        - id: user-service
          uri: http://localhost:8081
          predicates:
            - Path=/login,/logout,/home,/registration,/api/**,/css/**,/js/**,/webjars/**


        - id: chat-service
          uri: http://localhost:8082
          predicates:
            - Path=/chat/**,/api/messages/**,/chat.js,/ws/**,/api/friends

          filters:
            - name: PreserveHostHeader
      websocket:
        enabled: true

  # Чтобы cookies работали корректно с сессиями между сервисами

  servlet:
    session:
      cookie:
        same-site: none
        secure: false
